# Data Preprocessing for Influenza Vaccination Dashboard

This notebook cleans and transforms the CDC's Influenza Vaccination Coverage for All Ages (6+ Months) dataset for use in a D3.js-based data visualization dashboard. It includes:

- Dropping missing/invalid entries
- Filtering to focus on state-level, race/ethnicity-based data
- Parsing and formatting data for visualization
- Exporting final dataset to CSV and JSON formats

CDC dataset located at https://catalog.data.gov/dataset/influenza-vaccination-coverage-for-all-ages-6-months-bbec0


## 1. Load Libraries and Data

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("Influenza_Vaccination_Coverage.csv")

Observing dataset values

In [ ]:
df.head(5)

Vaccine Geography Type  Geography  FIPS Season/Survey Year  \
0  Seasonal Influenza       Counties  New Haven  9009               2018   
1  Seasonal Influenza       Counties  New Haven  9009               2021   
2  Seasonal Influenza       Counties  New Haven  9009               2020   
3  Seasonal Influenza       Counties  New Haven  9009               2021   
4  Seasonal Influenza       Counties  New Haven  9009               2018   

   Month Dimension Type            Dimension Estimate (%)    95% CI (%)  \
0      1     >=18 Years  Non-Medical Setting         45.5  43.9 to 47.2   
1      1     >=18 Years  Non-Medical Setting         53.0  46.0 to 60.9   
2      1            Age           >=18 Years         52.4  50.6 to 54.3   
3      1            Age           >=18 Years         50.2  45.4 to 55.8   
4      1            Age           >=18 Years         34.0  32.6 to 35.5   

   Sample Size  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN

Looking at data and datatypes within dataset

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 220729 entries, 0 to 220728
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype  
---  ------              --------------   -----  
 0   Vaccine             220729 non-null  object 
 1   Geography Type      220729 non-null  object 
 2   Geography           220729 non-null  object 
 3   FIPS                220729 non-null  int64  
 4   Season/Survey Year  220729 non-null  object 
 5   Month               220729 non-null  int64  
 6   Dimension Type      220729 non-null  object 
 7   Dimension           220729 non-null  object 
 8   Estimate (%)        220729 non-null  object 
 9   95% CI (%)          220495 non-null  object 
 10  Sample Size         197270 non-null  float64
dtypes: float64(1), int64(2), object(8)
memory usage: 18.5+ MB


In [ ]:
df[df["Geography"] == "District of Columbia"][df["Season/Survey Year"] == "2018-19"][df["Dimension Type"] == "Race and Ethnicity"]

<ipython-input-5-bff7885eb88f>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df["Geography"] == "District of Columbia"][df["Season/Survey Year"] == "2018-19"][df["Dimension Type"] == "Race and Ethnicity"]
<ipython-input-5-bff7885eb88f>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df["Geography"] == "District of Columbia"][df["Season/Survey Year"] == "2018-19"][df["Dimension Type"] == "Race and Ethnicity"]


Empty DataFrame
Columns: [Vaccine, Geography Type, Geography, FIPS, Season/Survey Year, Month, Dimension Type, Dimension, Estimate (%), 95% CI (%), Sample Size]
Index: []

## 2. Cleaning Missing and Invalid Values

Getting rid of samples with NaN sample size and no reported estimate, because won't help when exploring insights requiring those values

In [ ]:
df = df.dropna(subset=['Sample Size'])

In [ ]:
df['Estimate (%)'] = df['Estimate (%)'].replace('NR', np.nan)
df['Estimate (%)'] = df['Estimate (%)'].replace('NR †', np.nan)
df['Estimate (%)'] = df['Estimate (%)'].replace('NR *', np.nan)
df['Estimate (%)'] = df['Estimate (%)'].replace('NR â€\xa0', np.nan)
df = df.dropna(subset=['Estimate (%)'])

## 3. Filtering Relevant Data

In [ ]:
unique_values = df['Month'].unique()
unique_values

array([ 5,  4, 11, 10,  9,  1, 12,  3,  2,  8,  7])

In [ ]:
print(df.shape)
df.head(5)

(179677, 11)


Vaccine      Geography Type   Geography  FIPS  \
6   Seasonal Influenza  States/Local Areas  New Jersey    34   
7   Seasonal Influenza  States/Local Areas  New Jersey    34   
8   Seasonal Influenza  States/Local Areas  New Jersey    34   
9   Seasonal Influenza  States/Local Areas  New Jersey    34   
10  Seasonal Influenza  States/Local Areas  New Jersey    34   

   Season/Survey Year  Month      Dimension Type  \
6             2009-10      5  Race and Ethnicity   
7             2009-10      4  Race and Ethnicity   
8             2009-10     11  Race and Ethnicity   
9             2009-10     10  Race and Ethnicity   
10            2009-10      9  Race and Ethnicity   

                                         Dimension Estimate (%)  \
6   American Indian or Alaska Native, Non-Hispanic         57.7   
7   American Indian or Alaska Native, Non-Hispanic         57.7   
8                              Asian, Non-Hispanic         34.7   
9                              Asian, Non-Hispanic         24.8   
10                             Asian, Non-Hispanic         10.8   

        95% CI (%)  Sample Size  
6   40.2 to 75.2 ‡         48.0  
7   40.2 to 75.2 ‡         48.0  
8     29.1 to 40.3        552.0  
9     19.7 to 29.9        552.0  
10     6.6 to 15.0        552.0

Adding numerical year column and converting other columns to floats

In [ ]:
df.loc[:, 'Year'] = df['Season/Survey Year'].str.split('-').str[0].astype(int)
df['Estimate (%)'] = df['Estimate (%)'].astype(float)

In [ ]:
df.head()

Vaccine      Geography Type   Geography  FIPS  \
6   Seasonal Influenza  States/Local Areas  New Jersey    34   
7   Seasonal Influenza  States/Local Areas  New Jersey    34   
8   Seasonal Influenza  States/Local Areas  New Jersey    34   
9   Seasonal Influenza  States/Local Areas  New Jersey    34   
10  Seasonal Influenza  States/Local Areas  New Jersey    34   

   Season/Survey Year  Month      Dimension Type  \
6             2009-10      5  Race and Ethnicity   
7             2009-10      4  Race and Ethnicity   
8             2009-10     11  Race and Ethnicity   
9             2009-10     10  Race and Ethnicity   
10            2009-10      9  Race and Ethnicity   

                                         Dimension  Estimate (%)  \
6   American Indian or Alaska Native, Non-Hispanic          57.7   
7   American Indian or Alaska Native, Non-Hispanic          57.7   
8                              Asian, Non-Hispanic          34.7   
9                              Asian, Non-Hispanic          24.8   
10                             Asian, Non-Hispanic          10.8   

        95% CI (%)  Sample Size  Year  
6   40.2 to 75.2 ‡         48.0  2009  
7   40.2 to 75.2 ‡         48.0  2009  
8     29.1 to 40.3        552.0  2009  
9     19.7 to 29.9        552.0  2009  
10     6.6 to 15.0        552.0  2009

for purposes of easier dashboard getting rid of geography values that are not a state or territory

In [ ]:
unique_values = df['Geography'].unique()
print(unique_values, "length", unique_values.shape[0])

['New Jersey' 'Delaware' 'District of Columbia' 'Oklahoma' 'Oregon'
 'California' 'Indiana' 'Iowa' 'North Dakota' 'Nebraska' 'Region 4'
 'Missouri' 'Illinois' 'Minnesota' 'Mississippi' 'New York'
 'NY-City of New York' 'Vermont' 'Colorado' 'Maryland' 'Massachusetts'
 'Region 3' 'Region 2' 'Wyoming' 'West Virginia' 'Maine' 'Alabama'
 'Region 1' 'PA-Philadelphia' 'PA-Rest of state' 'Region 9' 'Tennessee'
 'Texas' 'United States' 'Puerto Rico' 'Montana' 'Rhode Island'
 'South Carolina' 'Arkansas' 'Nevada' 'Wisconsin' 'New Mexico' 'Alaska'
 'IL-Rest of state' 'Virginia' 'NY-Rest of state' 'North Carolina'
 'Kentucky' 'TX-Rest of state' 'U.S. Virgin Islands' 'Region 10'
 'Michigan' 'Pennsylvania' 'Florida' 'TX-City of Houston' 'New Hampshire'
 'Ohio' 'Region 7' 'Arizona' 'IL-City of Chicago' 'Idaho' 'Region 5'
 'Region 6' 'Hawaii' 'Kansas' 'Connecticut' 'Georgia' 'Guam' 'Utah'
 'Louisiana' 'TX-Bexar County' 'Washington' 'South Dakota' 'Region 8'] length 74


In [ ]:
df = df[~df['Geography'].str.contains('region|-', case=False, na=False)]

In [ ]:
unique_values = df['Geography'].unique()
print(unique_values, "length", unique_values.shape[0])

['New Jersey' 'Delaware' 'District of Columbia' 'Oklahoma' 'Oregon'
 'California' 'Indiana' 'Iowa' 'North Dakota' 'Nebraska' 'Missouri'
 'Illinois' 'Minnesota' 'Mississippi' 'New York' 'Vermont' 'Colorado'
 'Maryland' 'Massachusetts' 'Wyoming' 'West Virginia' 'Maine' 'Alabama'
 'Tennessee' 'Texas' 'United States' 'Puerto Rico' 'Montana'
 'Rhode Island' 'South Carolina' 'Arkansas' 'Nevada' 'Wisconsin'
 'New Mexico' 'Alaska' 'Virginia' 'North Carolina' 'Kentucky'
 'U.S. Virgin Islands' 'Michigan' 'Pennsylvania' 'Florida' 'New Hampshire'
 'Ohio' 'Arizona' 'Idaho' 'Hawaii' 'Kansas' 'Connecticut' 'Georgia' 'Guam'
 'Utah' 'Louisiana' 'Washington' 'South Dakota'] length 55


In [ ]:
print(df.shape)
df.head(1)

(144980, 12)


Vaccine      Geography Type   Geography  FIPS  \
6  Seasonal Influenza  States/Local Areas  New Jersey    34   

  Season/Survey Year  Month      Dimension Type  \
6            2009-10      5  Race and Ethnicity   

                                        Dimension  Estimate (%)  \
6  American Indian or Alaska Native, Non-Hispanic          57.7   

       95% CI (%)  Sample Size  Year  
6  40.2 to 75.2 ‡         48.0  2009

Filtering to get Dimension Type 'Race and Ethnicity'

In [ ]:
unique_values = df['Dimension Type'].unique()
print(unique_values, "length", unique_values.shape[0])

['Race and Ethnicity' 'Age' '>=18 Years' '6 Months - 17 Years'
 '>=65 Years' '50-64 Years' '18-49 Years' '18-64 Years'] length 8


In [ ]:
unique_values = df['Dimension'].unique()
print(unique_values, "length", unique_values.shape[0])

['American Indian or Alaska Native, Non-Hispanic' 'Asian, Non-Hispanic'
 '>=65 Years' 'White, Non-Hispanic' '50-64 Years' 'Hispanic'
 '18-49 Years at High Risk' '>=18 Years'
 'Other or Multiple Races, Non-Hispanic' '18-49 Years not at High Risk'
 'Non-Medical Setting' 'Black, Non-Hispanic' '6 Months - 17 Years'
 '>=6 Months' '6 Months - 4 Years' '5-12 Years' 'Pharmacy/Store'
 'Workplace' 'Medical Setting' 'School' '18-64 Years'
 '18-64 Years not at High Risk' '18-64 Years at High Risk' '18-49 Years'
 '13-17 Years' 'Greater 65' 'Greater than 6 Months flu'
 'Greater than 18 Years flu' '25-64 Years not in Initial Target Group'
 '25-64 Years at High Risk'
 '6 Months - 64 Years at High Risk (Initial Target Group)'] length 31


In [ ]:
print(df[df['Dimension'] == 'American Indian or Alaska Native, Non-Hispanic'].shape)
print(df[df['Dimension'] == 'Asian, Non-Hispanic'].shape)
print(df[df['Dimension'] == 'Black, Non-Hispanic'].shape)
print(df[df['Dimension'] == 'Hispanic'].shape)
print(df[df['Dimension'] == 'White, Non-Hispanic'].shape)

(879, 12)
(1067, 12)
(7571, 12)
(8234, 12)
(8900, 12)


In [ ]:
filtered_df = df[df['Dimension Type'] == "Race and Ethnicity"]
print(filtered_df.shape)

(34610, 12)


In [ ]:
unique_values = filtered_df['Dimension'].unique()
print(unique_values, "length", unique_values.shape[0])

['American Indian or Alaska Native, Non-Hispanic' 'Asian, Non-Hispanic'
 'White, Non-Hispanic' 'Hispanic' 'Other or Multiple Races, Non-Hispanic'
 'Black, Non-Hispanic'] length 6


## 4. Export  Cleaned Data

In [ ]:
filtered_df.to_json('cleaned_data.json', orient='records', indent=2)

In [ ]:
filtered_df.to_csv('cleaned_data.csv')

## 5. Quick Data Exploration (Optional)

checking max estimate for seasonal influenza

In [ ]:
m_df = filtered_df[filtered_df['Vaccine'].str.contains('Seasonal Influenza', na=False)]

In [ ]:
max = m_df['Estimate (%)'].max()
max

88.8

In [ ]:
(int) ((max / 5) + 1) * 5

90

In [ ]:
m_df[m_df["Estimate (%)"] > 75]

Vaccine      Geography Type             Geography  FIPS  \
1949    Seasonal Influenza  States/Local Areas  District of Columbia    11   
1992    Seasonal Influenza  States/Local Areas  District of Columbia    11   
1993    Seasonal Influenza  States/Local Areas  District of Columbia    11   
7508    Seasonal Influenza  States/Local Areas          North Dakota    38   
7509    Seasonal Influenza  States/Local Areas          North Dakota    38   
7510    Seasonal Influenza  States/Local Areas          North Dakota    38   
7511    Seasonal Influenza  States/Local Areas          North Dakota    38   
70814   Seasonal Influenza  States/Local Areas  District of Columbia    11   
70815   Seasonal Influenza  States/Local Areas  District of Columbia    11   
72085   Seasonal Influenza  States/Local Areas  District of Columbia    11   
72086   Seasonal Influenza  States/Local Areas  District of Columbia    11   
72087   Seasonal Influenza  States/Local Areas  District of Columbia    11   
72088   Seasonal Influenza  States/Local Areas  District of Columbia    11   
110039  Seasonal Influenza  States/Local Areas              Arkansas     5   
110040  Seasonal Influenza  States/Local Areas              Arkansas     5   
110042  Seasonal Influenza  States/Local Areas              Arkansas     5   
110043  Seasonal Influenza  States/Local Areas              Arkansas     5   
140352  Seasonal Influenza  States/Local Areas  District of Columbia    11   
140361  Seasonal Influenza  States/Local Areas  District of Columbia    11   
140362  Seasonal Influenza  States/Local Areas  District of Columbia    11   
140363  Seasonal Influenza  States/Local Areas  District of Columbia    11   
175213  Seasonal Influenza  States/Local Areas          South Dakota    46   
175214  Seasonal Influenza  States/Local Areas          South Dakota    46   
175217  Seasonal Influenza  States/Local Areas          South Dakota    46   
175218  Seasonal Influenza  States/Local Areas          South Dakota    46   
175219  Seasonal Influenza  States/Local Areas          South Dakota    46   
178328  Seasonal Influenza  States/Local Areas         New Hampshire    33   
178329  Seasonal Influenza  States/Local Areas         New Hampshire    33   
178330  Seasonal Influenza  States/Local Areas         New Hampshire    33   
178337  Seasonal Influenza  States/Local Areas         New Hampshire    33   

       Season/Survey Year  Month      Dimension Type  \
1949              2021-22      3  Race and Ethnicity   
1992              2021-22      4  Race and Ethnicity   
1993              2021-22      5  Race and Ethnicity   
7508              2009-10      5  Race and Ethnicity   
7509              2009-10      4  Race and Ethnicity   
7510              2009-10      3  Race and Ethnicity   
7511              2009-10      2  Race and Ethnicity   
70814             2021-22      1  Race and Ethnicity   
70815             2021-22      2  Race and Ethnicity   
72085             2023-24      2  Race and Ethnicity   
72086             2023-24      3  Race and Ethnicity   
72087             2023-24      4  Race and Ethnicity   
72088             2023-24      5  Race and Ethnicity   
110039            2009-10      5  Race and Ethnicity   
110040            2009-10      4  Race and Ethnicity   
110042            2009-10      3  Race and Ethnicity   
110043            2009-10      2  Race and Ethnicity   
140352            2022-23      5  Race and Ethnicity   
140361            2022-23      3  Race and Ethnicity   
140362            2022-23      4  Race and Ethnicity   
140363            2022-23      5  Race and Ethnicity   
175213            2014-15      1  Race and Ethnicity   
175214            2014-15      2  Race and Ethnicity   
175217            2014-15      3  Race and Ethnicity   
175218            2014-15      4  Race and Ethnicity   
175219            2014-15      5  Race and Ethnicity   
178328            2009-10      2  Race and Ethnicity   
178329            2009-10      3

Only three different vaccine categories

In [ ]:
unique_values = filtered_df['Vaccine'].unique()
print(unique_values, "length", unique_values.shape[0])

['Seasonal Influenza' 'Any Influenza Vaccination, Seasonal or H1N1'
 'Influenza A (H1N1) 2009 Monovalent'] length 3


Some Messing with Data to figure out how to use it with D3.js

In [ ]:
az_df = filtered_df[filtered_df["Geography"] == "New Jersey"]

In [ ]:
unique_values = az_df['Year'].unique()
print(unique_values, "length", unique_values.shape[0])

[2009 2010 2021 2020 2019 2017 2016 2015 2014 2013 2012 2011 2023 2022] length 14


In [ ]:
year_df = az_df[az_df["Year"] == 2010]

In [ ]:
unique_values = year_df['Month'].unique()
print(unique_values, "length", unique_values.shape[0])

[ 9  8  2  1 12 11 10  4  3  5] length 10


In [ ]:
unique_values = year_df['Dimension'].unique()
print(unique_values, "length", unique_values.shape[0])

['Hispanic' 'Other or Multiple Races, Non-Hispanic' 'Black, Non-Hispanic'
 'White, Non-Hispanic'] length 4


In [ ]:
race_df = year_df[year_df["Dimension"] == 'White, Non-Hispanic']
race_df.shape

(10, 12)

In [ ]:
unique_values = race_df['Month'].unique()
print(unique_values, "length", unique_values.shape[0])

[ 5  4  3  2  1 12 11 10  9  8] length 10


In [ ]:
v_df = race_df[race_df['Vaccine'].str.contains('Seasonal Influenza', na=False)]

In [ ]:
v_df

Vaccine      Geography Type   Geography  FIPS  \
165733  Seasonal Influenza  States/Local Areas  New Jersey    34   
165734  Seasonal Influenza  States/Local Areas  New Jersey    34   
165735  Seasonal Influenza  States/Local Areas  New Jersey    34   
165742  Seasonal Influenza  States/Local Areas  New Jersey    34   
165743  Seasonal Influenza  States/Local Areas  New Jersey    34   
165908  Seasonal Influenza  States/Local Areas  New Jersey    34   
165909  Seasonal Influenza  States/Local Areas  New Jersey    34   
165910  Seasonal Influenza  States/Local Areas  New Jersey    34   
165916  Seasonal Influenza  States/Local Areas  New Jersey    34   
165917  Seasonal Influenza  States/Local Areas  New Jersey    34   

       Season/Survey Year  Month      Dimension Type            Dimension  \
165733            2010-11      5  Race and Ethnicity  White, Non-Hispanic   
165734            2010-11      4  Race and Ethnicity  White, Non-Hispanic   
165735            2010-11      3  Race and Ethnicity  White, Non-Hispanic   
165742            2010-11      2  Race and Ethnicity  White, Non-Hispanic   
165743            2010-11      1  Race and Ethnicity  White, Non-Hispanic   
165908            2010-11     12  Race and Ethnicity  White, Non-Hispanic   
165909            2010-11     11  Race and Ethnicity  White, Non-Hispanic   
165910            2010-11     10  Race and Ethnicity  White, Non-Hispanic   
165916            2010-11      9  Race and Ethnicity  White, Non-Hispanic   
165917            2010-11      8  Race and Ethnicity  White, Non-Hispanic   

        Estimate (%)    95% CI (%)  Sample Size  Year  
165733          45.0  43.1 to 46.9       9947.0  2010  
165734          44.7  42.8 to 46.6       9947.0  2010  
165735          44.3  42.4 to 46.2       9947.0  2010  
165742          43.6  41.8 to 45.4       9947.0  2010  
165743          42.3  40.5 to 44.1       9947.0  2010  
165908          40.4  38.6 to 42.2       9947.0  2010  
165909          37.7  36.0 to 39.4       9947.0  2010  
165910          28.2  26.7 to 29.7       9947.0  2010  
165916           8.9    7.9 to 9.9       9947.0  2010  
165917           1.0    0.8 to 1.2       9947.0  2010

In [ ]:
v_df['Estimate (%)'].mean()

np.float64(31.890000000000004)

In [ ]:
v_df['Sample Size'].mean()

np.float64(5614.0)

### Notes on Dataset
FIPS is Federal Information Processing Standard code (numeric code used to identify states and counties)

Estimate is estimated percentage of population that received vaccination

95% CI is 95% Confidence Interval (true value is expected to fall within range 95% of the time)

In [ ]:
az_df = filtered_df[filtered_df["Geography"] == "Arizona"]
az_df.head(5)

Vaccine      Geography Type  \
95824  Any Influenza Vaccination, Seasonal or H1N1  States/Local Areas   
95825  Any Influenza Vaccination, Seasonal or H1N1  States/Local Areas   
95826  Any Influenza Vaccination, Seasonal or H1N1  States/Local Areas   
95827  Any Influenza Vaccination, Seasonal or H1N1  States/Local Areas   
95828  Any Influenza Vaccination, Seasonal or H1N1  States/Local Areas   

      Geography  FIPS Season/Survey Year  Month      Dimension Type  \
95824   Arizona     4            2009-10      9  Race and Ethnicity   
95825   Arizona     4            2009-10     10  Race and Ethnicity   
95826   Arizona     4            2009-10     11  Race and Ethnicity   
95827   Arizona     4            2009-10     12  Race and Ethnicity   
95828   Arizona     4            2009-10      1  Race and Ethnicity   

                 Dimension  Estimate (%)      95% CI (%)  Sample Size  Year  
95824  Asian, Non-Hispanic          16.0     7.4 to 24.6        134.0  2009  
95825  Asian, Non-Hispanic          33.4  14.8 to 52.0 ‡        134.0  2009  
95826  Asian, Non-Hispanic          43.3  25.2 to 61.4 ‡        134.0  2009  
95827  Asian, Non-Hispanic          52.5  36.0 to 69.0 ‡        134.0  2009  
95828  Asian, Non-Hispanic          54.0  37.9 to 70.1 ‡        134.0  2009

In [ ]:
unique_values = az_df['Season/Survey Year'].unique()
print(unique_values, "length", unique_values.shape[0])

['2009-10' '2010-11' '2021-22' '2020-21' '2019-20' '2018-19' '2016-17'
 '2017-18' '2012-13' '2013-14' '2014-15' '2015-16' '2011-12' '2023-24'
 '2022-23'] length 15


In [ ]:
df_17 = az_df[az_df["Season/Survey Year"] == "2017-18"]
print(df_17['Month'].unique())
df_17[df_17['Month'] == 1].shape

[ 8  9 10 11 12  1  2  3  4  5  7]


(4, 12)

In [ ]:
az_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 696 entries, 95824 to 212123
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Vaccine             696 non-null    object 
 1   Geography Type      696 non-null    object 
 2   Geography           696 non-null    object 
 3   FIPS                696 non-null    int64  
 4   Season/Survey Year  696 non-null    object 
 5   Month               696 non-null    int64  
 6   Dimension Type      696 non-null    object 
 7   Dimension           696 non-null    object 
 8   Estimate (%)        696 non-null    float64
 9   95% CI (%)          696 non-null    object 
 10  Sample Size         696 non-null    float64
 11  Year                696 non-null    int64  
dtypes: float64(2), int64(3), object(7)
memory usage: 70.7+ KB
